{
 "title": "Top transactions",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Service name",
    "query": {
     "query": "label_values(span_duration_millis_count{span_kind=\"SERVER\"}, job)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Top transactions",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(transaction_name) (rate(span_duration_millis_sum{span_kind=\"SERVER\"}[$__rate_interval])) / ignoring(transaction_name) group_left sum(rate(span_duration_millis_sum{span_kind=\"SERVER\"}[$__rate_interval])) * 100",
     "legendFormat": "{{transaction_name}}"
    },
    {
     "expr": "sum by(transaction_name) (rate(span_duration_millis_sum{span_kind=\"SERVER\"}[$__rate_interval])) / sum by(transaction_name) (rate(span_duration_millis_count{span_kind=\"SERVER\"}[$__rate_interval]))",
     "legendFormat": "{{transaction_name}}"
    },
    {
     "expr": "sum by(transaction_name) (rate(span_duration_millis_count{span_kind=\"SERVER\"}[$__rate_interval]))",
     "legendFormat": "{{transaction_name}}"
    },
    {
     "expr": "sum by(transaction_name) (rate(span_duration_millis_count{job=\"$job\", span_kind=\"SERVER\", http_status_code!~\"2\\\\d\\\\d\" }[$__rate_interval])) / sum by(transaction_name) (rate(span_duration_millis_count{job=\"$job\", span_kind=\"SERVER\"}[$__rate_interval])) * 100"
    }
   ]
  },
  {
   "title": "Total time spent (top 5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5, sum by(transaction_name) (rate(span_duration_millis_sum{span_kind=\"SERVER\"}[$__rate_interval])) / ignoring(transaction_name) group_left sum(rate(span_duration_millis_sum{span_kind=\"SERVER\"}[$__rate_interval])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (top 5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, sum by(transaction_name) (rate(span_duration_millis_sum{job=\"$job\", span_kind=\"SERVER\"}[$__rate_interval])) / sum by(transaction_name) (rate(span_duration_millis_count{job=\"$job\", span_kind=\"SERVER\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (top 5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(5, sum by(transaction_name) (rate(span_duration_millis_count{span_kind=\"SERVER\", job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate (top 5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5, sum by(transaction_name) (rate(span_duration_millis_count{job=\"$job\", span_kind=\"SERVER\", http_status_code!~\"2\\\\d\\\\d\" }[$__rate_interval])) / sum by(transaction_name) (rate(span_duration_millis_count{job=\"$job\", span_kind=\"SERVER\"}[$__rate_interval])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}