{
 "title": "Transaction details",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Service name",
    "query": {
     "query": "label_values(span_duration_millis_count{span_kind=\"SERVER\"}, job)"
    }
   },
   {
    "name": "transaction_name",
    "label": "Transaction",
    "query": {
     "query": "label_values(span_duration_millis_count{span_kind=\"SERVER\", job=\"$job\"}, transaction_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(span_duration_millis_sum{job=\"$job\", transaction_name=\"$transaction_name\", span_kind=\"SERVER\"}[$__rate_interval])) / sum(rate(span_duration_millis_count{job=\"$job\", transaction_name=\"$transaction_name\", span_kind=\"SERVER\"}[$__rate_interval]))",
     "legendFormat": "Response time"
    },
    {
     "expr": "sum by(span_name, http_url) (rate(span_duration_millis_sum{job=\"$job\", transaction_name=\"$transaction_name\",span_kind!=\"SERVER\"}[$__rate_interval])) / ignoring(span_name, http_url) group_left sum(rate(span_duration_millis_count{job=\"$job\", transaction_name=\"$transaction_name\", span_kind=\"SERVER\"}[$__rate_interval]))",
     "legendFormat": "{{span_name}} {{http_url}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(span_duration_millis_bucket{job=\"$job\", transaction_name=\"$transaction_name\", span_kind=\"SERVER\"}[$__rate_interval])))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(span_duration_millis_bucket{job=\"$job\", transaction_name=\"$transaction_name\", span_kind=\"SERVER\"}[$__rate_interval])))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(span_duration_millis_bucket{job=\"$job\", transaction_name=\"$transaction_name\", span_kind=\"SERVER\"}[$__rate_interval])))",
     "legendFormat": "median"
    },
    {
     "expr": "sum(rate(span_duration_millis_sum{job=\"$job\", transaction_name=\"$transaction_name\", span_kind=\"SERVER\"}[$__rate_interval])) / sum(rate(span_duration_millis_count{job=\"$job\", transaction_name=\"$transaction_name\", span_kind=\"SERVER\"}[$__rate_interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(span_duration_millis_count{span_kind=\"SERVER\", job=\"$job\", transaction_name=\"$transaction_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(http_status_code) (rate(span_duration_millis_count{job=\"$job\", transaction_name=\"$transaction_name\", span_kind=\"SERVER\", http_status_code!~\"2\\\\d\\\\d\" }[$__rate_interval])) / ignoring(http_status_code) group_left sum(rate(span_duration_millis_count{job=\"$job\", transaction_name=\"$transaction_name\", span_kind=\"SERVER\"}[$__rate_interval])) * 100) or on() vector(0) ",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  }
 ]
}